config/routes.rb
# frozen_string_literal: true

require 'sidekiq/web'

Rails.application.routes.draw do
  root 'public#home'

  devise_for(
    :users,
    path: '',
    path_names: {
      sign_in: 'login',
      sign_out: 'logout',
      new_user_password: 'reset'
    },
    controllers: {
      registrations: 'users/registrations',
      sessions: 'users/sessions',
      invitations: 'users/invitations'
    }
  )

  devise_scope :user do
    get    '/users/:id/edit',     to: 'users/registrations#admin_edit',   as: 'admin_edit'
    put    '/users/:id',          to: 'users/registrations#admin_update', as: 'admin_update'
  end

  authenticate :user, lambda { |u| u.permitted?(:admin, strict: true) } do
    mount Sidekiq::Web => '/sidekiq'
  end

  ### Short URLs
  get     '/e/:slug',         to: 'events/events#slug',         as: 'event_slug'
  get     '/a/:id',           to: 'public#announcement_direct', as: 'short_announcement'
  get     '/b/:year/:month',  to: 'public#bilge',               as: 'short_bilge'
  get     '/m/:year/:month',  to: 'members#find_minutes',       as: 'short_minutes'
  get     '/ex/:year/:month', to: 'members#find_minutes',       as: 'short_excom', defaults: { minutes_excom: true }

  ### Profile management
  as :user do
    get    '/profile',            to: 'user#show'
    get    '/profile/edit',       to: 'users/registrations#edit'
    put    '/profile/edit',       to: 'users/registrations#update'
    get    '/reset',              to: 'devise/passwords#new'

    get    '/profile/tokens',     to: 'user#tokens'
    delete '/profile/tokens/:id', to: 'user#revoke_token', as: 'revoke_token'
  end

  ### Markdown pages
  %i[
    home about join requirements vsc education calendar civic history links
    members welcome user_help
  ].each do |md|
    get   "/#{md}",      to: "public##{md}", as: md,    defaults: { page_name: md } unless md.in?(%i[home members user_help welcome])
    get   "/#{md}/edit", to: 'members#edit_markdown',   defaults: { page_name: md }
    patch "/#{md}/edit", to: 'members#update_markdown', defaults: { page_name: md }
  end

  get     '/home',            to: redirect('/')
  get     '/members',         to: 'members#members'
  get     '/user_help',       to: 'members#user_help'
  get     '/welcome',         to: 'members#welcome'
  get     '/edit/:page_name', to: 'members#edit_markdown',   as: 'edit_page'
  patch   '/edit/:page_name', to: 'members#update_markdown', as: 'update_page'

  ### Static pages
  get     '/refunds',        to: 'braintree#refunds'
  get     '/payment_terms',  to: 'braintree#terms'
  get     '/flags',          to: 'flags#flags'
  get     '/flags/national', to: 'flags#national'
  get     '/tridents',       to: 'flags#tridents'
  get     '/intersections',  to: 'flags#intersections'
  get     '/signals',        to: 'flags#signals'
  get     '/complete',       to: 'public#complete'
  get     '/cancelled',      to: 'public#cancelled'

  ### Pre-loaded pages
  get     '/ranks',            to: 'members#ranks'
  get     '/auto_permissions', to: 'permissions#auto'

  ### Functional pages
  get     '/bridge', to: 'bridge#list'
  get     '/store',  to: 'public#store'

  # Photo gallery
  get     '/photos',       to: 'gallery#index'
  post    '/assign_photo', to: 'user#assign_photo'

  # Membership
  get     '/apply',        to: 'member_applications#new'
  get     '/applications', to: 'member_applications#review'
  get     '/dues',         to: 'members#dues'
  get     '/glyc_members', to: 'members#glyc_members'
  post    '/glyc_members', to: 'members#update_glyc_members'

  # Float plans
  resources :float_plans, only: %i[index show new create] do
    patch :refresh, on: :member
  end

  # Admin utilities
  namespace :admin do
    # S3 Link Generator
    get    '/s3',                        to: 'links#s3'
    post   '/s3',                        to: 'links#s3'

    # Versions
    get    '/versions/:model/:id',       to: 'versions#show',   as: 'show_versions'
    get    '/versions/:model/:id/:a/:b', to: 'versions#diff',   as: 'diff_versions'
    post   '/versions/:model/:id/:a/:b', to: 'versions#diff'
    patch  '/versions/:model/:id/:a',    to: 'versions#revert', as: 'revert_version'
    get    '/versions(/:model)',         to: 'versions#index',  as: 'versions'

    # Logo Generator
    get    '/logo',                      to: 'logos#logo'

    # Promo Codes
    get    '/promo_codes',               to: 'promo_codes#list'
    get    '/promo_codes/new',           to: 'promo_codes#new',      as: 'new_promo_code'
    put    '/promo_codes/new',           to: 'promo_codes#create',   as: 'create_promo_code'
    patch  '/promo_codes/:id/activate',  to: 'promo_codes#activate', as: 'activate_promo_code'
    delete '/promo_codes/:id/expire',    to: 'promo_codes#expire',   as: 'expire_promo_code'

    # Send Message
    resources :messages, only: %i[new create]
    resources :emails, only: %i[new create]

    # Generic Payments
    get    '/generic_payments',          to: 'generic_payments#index'
    get    '/generic_payments/new',      to: 'generic_payments#new'
    post   '/generic_payments',          to: 'generic_payments#create'

    # Import Logs
    resources :import_logs, only: %i[index show]

    # DMARC Reports
    resources :dmarc_reports, only: %i[index show create]

    # Placecards
    resources :placecards, only: %i[new create]
  end

  # Newsletter
  get     '/newsletter',         to: 'public#newsletter'
  get     '/bilge/:year/:month', to: 'public#bilge',         as: 'bilge'
  post    '/bilge',              to: 'members#upload_bilge', as: 'upload_bilge'
  get     '/bilge(/:year)',      to: redirect('/newsletter')

  # Announcements
  get     '/announcement/:id',        to: 'public#announcement_direct',  as: 'announcement'
  post    '/announcement',            to: 'members#upload_announcement', as: 'upload_announcement'
  patch   '/announcement/:id/hide',   to: 'members#hide_announcement',   as: 'hide_announcement'
  patch   '/announcement/:id/unhide', to: 'members#unhide_announcement', as: 'unhide_announcement'
  delete  '/announcement/:id',        to: 'members#remove_announcement', as: 'remove_announcement'
  get     '/announcement',            to: redirect('/newsletter')
  get     '/announcements',           to: redirect('/newsletter')

  # Minutes
  get     '/minutes',              to: 'members#minutes'
  post    '/minutes',              to: 'members#upload_minutes', as: 'upload_minutes'
  get     '/minutes/:year/:month', to: 'members#find_minutes',   as: 'get_minutes'
  get     '/excom/:year/:month',   to: 'members#find_minutes',   as: 'get_minutes_excom', defaults: { excom: 'true' }
  get     '/minutes(/:year)', to: redirect('/minutes')

  # Registration
  put     '/register',        to: 'public#register', as: 'public_register'
  post    '/register',        to: 'public#register', as: 'long_register'

  # Subscriptions
  post    '/subscribe/:id',   to: 'members#subscribe',   as: 'subscribe'
  post    '/unsubscribe/:id', to: 'members#unsubscribe', as: 'unsubscribe'

  # User invitation
  put     '/invite/:id', to: 'user#invite', as: 'invite'
  put     '/invite_all', to: 'user#invite_all'

  # Markdown files and header images
  get     '/file',               to: 'file#new',            as: 'file'
  post    '/file/upload',        to: 'file#create',         as: 'upload_file'
  delete  '/file/:id/destroy',   to: 'file#destroy',        as: 'remove_file'
  get     '/header',             to: 'file#new_header',     as: 'header'
  post    '/header/upload',      to: 'file#create_header',  as: 'upload_header'
  delete  '/header/:id/destroy', to: 'file#destroy_header', as: 'remove_header'

  # Locations and Event Types
  %i[location event_type].each do |model|
    get     "/#{model}s",               to: "#{model}s#list",    as: "#{model}s"
    get     "/#{model}s/new",           to: "#{model}s#new",     as: "new_#{model}"
    post    "/#{model}s/create",        to: "#{model}s#create",  as: "create_#{model}"
    get     "/#{model}s/:id/edit",      to: "#{model}s#edit",    as: "edit_#{model}"
    patch   "/#{model}s/:id/update",    to: "#{model}s#update",  as: "update_#{model}"
    delete  "/#{model}s/:id/remove",    to: "#{model}s#remove",  as: "remove_#{model}"
    get     "/#{model}s/refresh(/:id)", to: "#{model}s#refresh", as: "refresh_#{model}s"
  end

  # Roster Historical Records
  namespace :roster do
    resource :award_recipients
    resource :past_commanders
    resource :archive_files
  end

  # Photo Galleries
  post    '/album/new',       to: 'gallery#add_album',    as: 'new_album'
  get     '/album/:id',       to: 'gallery#show',         as: 'show_album'
  delete  '/album/:id',       to: 'gallery#remove_album', as: 'remove_album'
  post    '/album/photo',     to: 'gallery#upload_photo', as: 'upload_photo'
  delete  '/album/photo/:id', to: 'gallery#remove_photo', as: 'remove_photo'

  # Editor auto-show state setters
  post    '/auto_show', to: 'user#auto_show', as: 'auto_show'
  post    '/auto_hide', to: 'user#auto_hide', as: 'auto_hide'

  # Member Applications
  put     '/apply',                   to: 'member_applications#apply',   as: 'submit_application'
  get     '/applied(/:token)',        to: 'member_applications#applied', as: 'applied'
  patch   '/approve_application/:id', to: 'member_applications#approve', as: 'approve_application'

  # Roster
  get     '/roster',                    to: 'members#roster',        as: 'roster'
  # get  '/update_roster',             to: 'members#update_roster', as: 'update_roster'
  # post '/update_roster',             to: 'members#upload_roster'
  get     '/roster/gen(/:orientation)', to: 'members#roster_gen',    as: 'roster_gen', defaults: { orientation: 'detailed' }

  # OTW Trainings
  get     '/otw',                to: 'otw_trainings#user'
  get     '/otw/progress(/:id)', to: 'otw_trainings#user_progress', as: 'otw_progress'
  get     '/otw/requests',       to: 'otw_trainings#list_requests'

app/models/user/lockable.rb
# frozen_string_literal: true

class User
  module Lockable
    extend ActiveSupport::Concern

    def locked?
      locked_at.present?
    end

    def lock
      update(locked_at: Time.zone.now)
    end

    def unlock
      update(locked_at: nil)
    end
  end
end

app/controllers/concerns/otw_trainings/user.rb
# frozen_string_literal: true

module OTWTrainings
  module User
    def user
      @otw_requests = current_user&.otw_trainings&.where(
        'otw_training_users.created_at > ?', Time.zone.today - 6.months
      )
      @otw_credits = @otw_trainings.select { |o| o.course_key.in?(current_user.completions.keys) }
    end

    def user_request
      @otw = OTWTraining.find_by(id: otw_user_params[:id])

      if (otw_request = OTWTrainingUser.find_or_create_by(otw_training: @otw, user: current_user))
        user_request_succeeded(otw_request)
      else
        user_request_failed(otw_request)
      end
    end

    def user_progress
      requirements_path = Rails.root.join('config/boc_requirements.json')
      @boc_requirements = JSON.parse(File.read(requirements_path)).deep_symbolize_keys!
      @completions = pick_user.completions
    end

  private

    def otw_user_params
      params.permit(:id)
    end

    def pick_user
      @user = ::User.find_by(id: otw_user_params[:id]) || current_user
    end

    def levels
      @levels = {
        inland: 'BOC_IN',
        coastal: 'BOC_CN',
        advanced_coastal: 'BOC_ACN',
        offshore: 'BOC_ON'
      }
    end

    def icons
      @icons = {
        'Course' => FA::Icon.p('users-class', style: :duotone, title: 'Course'),
        'Seminar' => FA::Icon.p('presentation', style: :duotone, title: 'Seminar'),
        'Skill' => FA::Icon.p('ship', style: :duotone, title: 'Skill')
      }
    end
  end
end

app/controllers/concerns/user/edit.rb
# frozen_string_literal: true

class User
  module Edit
    def assign_photo
      photo = clean_params[:photo]

      if photo.present? && User.find_by(id: clean_params[:id]).assign_photo(local_path: photo.path)
        flash[:success] = 'Successfully assigned profile photo!'
      else
        flash[:alert] = 'Unable to assign profile photo.'
      end

      redirect_to assign_photo_dest_path
    end

    def auto_show
      auto_shows << clean_params[:page_name]
      head :ok
    end

    def auto_hide
      auto_shows.delete(clean_params[:page_name])
      head :ok
    end

  private

    def auto_shows
      session[:auto_shows] ||= Set.new
    end

    def assign_photo_dest_path
      case clean_params[:redirect_to]
      when 'show'
        user_path(clean_params[:id])
      when 'bridge'
        bridge_path
      else # 'list'
        users_path
      end
    end
  end
end

app/controllers/concerns/user/import.rb
# frozen_string_literal: true

class User
  module Import
    ACCEPTABLE_CONTENT_TYPES = %w[
      text/csv text/plain application/octet-stream application/vnd.ms-excel
    ].freeze

    def import; end

    def do_import
      uploaded_file = clean_params[:import_file]
      return only_csv unless uploaded_file.content_type.in?(ACCEPTABLE_CONTENT_TYPES)

      begin
        importer = ImportUsers::Import.new(
          upload_import_file(uploaded_file), lock: clean_params[:lock_missing]
        )
        @import_proto = importer.call
        @log_timestamp = importer.log_timestamp
        @import_log_id = importer.import_log_id
        import_success
      rescue StandardError => e
        import_failure(e)
      end
    end

    def automatic_update
      run_automatic_import(dryrun: false)
    end

    def automatic_update_dryrun
      run_automatic_import(dryrun: true)
    end

    def invite_imported_users
      new_users = User.invitable_from(invite_imported_params[:users])

      if new_users.empty?
        flash[:notice] = 'No invitable users found.'
      else
        new_users.each(&:invite!)
        flash[:success] = "Successfully invited #{new_users.count} newly imported users!"
      end

      redirect_to(admin_import_log_path(invite_imported_params[:import_log_id]))
    end

  private

    def invite_imported_params
      params.permit(:import_log_id, users: [])
    end

    def only_csv
      flash.now[:alert] = 'You can only upload CSV files.'
      render :import
    end

    def upload_import_file(uploaded_file)
      import_path = Rails.root.join("tmp/run/#{Time.now.to_i}-users_import.csv").to_s
      file = File.open(import_path, 'w+')
      file.write(uploaded_file.read)
      file.close
      import_path
    end

    def run_automatic_import(dryrun:)
      @result = AutomaticUpdateJob.new.perform(
        current_user.id,
        dryrun: dryrun,
        via: 'UI',
        lock: clean_params[:lock_missing] == 'true'
      )
      @result.success? ? import_success : import_failure
    end

    def import_success
      flash.now[:success] = "Successfully #{@dryrun ? 'tested importing' : 'imported'} user data."
      @import_proto = @result.import_proto
      @log_timestamp = @result.log_timestamp
      @import_log_id = @result.import_log_id
      render :import
    end

    def import_failure
      flash.now[:alert] = 'Unable to import user data.'
      flash.now[:error] = @result.error.message
      Bugsnag.notify(@result.error)
      render :import
    end
  end
end

app/controllers/concerns/user/insignia.rb
# frozen_string_literal: true

class User
  module Insignia
    def insignia
      grade, grade_title = grade_and_title
      membership, membership_title = membership_and_title

      @insignia = { grade: grade, membership: membership }

      @insignia_title = {
        grade: grade_title, membership: membership_title,
        mm: @user.mm&.positive? ? "#{@user.mm} Merit Marks" : nil
      }
    end

  private

    def grade_and_title
      return if @user.grade.blank?

      if @user.ed_pro.present? && @user.grade != 'SN'
        [
          "#{@user.grade.downcase}_edpro",
          "Grade: #{@user.grade} with Educational Proficiency"
        ]
      else
        [@user.grade.downcase, "Grade: #{@user.grade}"]
      end
    end

    def membership_and_title
      return unless @user.life.present? || @user.senior.present?

      if @user.life.present?
        [:life, 'Life Member']
      elsif @user.senior.present?
        [:senior, 'Senior Member']
      end
    end
  end
end

app/controllers/concerns/user/instructors.rb
# frozen_string_literal: true

class User
  module Instructors
    def instructors
      load_instructor_data
      return unless @highlight.present? && @only

      @instructors = filter_instructors
    end

  private

    def load_instructor_data
      @highlight = clean_params[:key].to_s.upcase
      @only = clean_params[:only] == '1'
      @instructors = User.unlocked.alphabetized.includes(:course_completions).where(
        'id_expr > ? OR (cpr_aed_expires_at IS NOT NULL AND cpr_aed_expires_at > ?)',
        Time.zone.now, Time.zone.now
      )
      @keys = %w[ABC CPR/AED S P AP JN N CP EM ID ME MCS MES EN RA SA WE] << %w[Exam SN]
    end

    def filter_instructors
      return abc_instructors if @highlight == 'ABC'
      return sn_instructors if @highlight == 'SN'
      return cpr_instructors if @highlight == 'CPR/AED'
      return me_instructors if @highlight.in?(%w[MCS MES EN])

      course_instructors
    end

    def abc_instructors
      @instructors.select { |u| u.id_expr.present? && u.id_expr > Time.zone.now }
    end

    def sn_instructors
      @instructors.select { |u| u.grade == 'SN' }
    end

    def cpr_instructors
      @instructors.select(&:cpr_aed?)
    end

    def me_instructors
      @instructors.select do |u|
        u.completions.key?(@highlight) || u.completions.key?('ME')
      end
    end

    def course_instructors
      @instructors.select { |u| u.completions.key?(@highlight) }
    end
  end
end

app/views/user/_invite_imported_form.html.slim
= form_tag(invite_imported_users_path) do
  = hidden_field_tag(:import_log_id, 304)
  - users.each do |user|
    = hidden_field_tag('users[]', user.id)
  = submit_tag("Import #{users.count} New Users", class: 'big')

app/views/user/_jobcodes.html.slim
- if jobcodes.any?
  h2 Jobs
  .table#jobs.striped
    .table-row.header
      .table-cell Code
      .table-cell Year
      .table-cell Level
      .table-cell
      .table-cell Description
    - jobcodes.each do |jobcode|
      .table-row class=('outdated' unless jobcode.current_year?)
        .table-cell = jobcode.code
        .table-cell = jobcode.year
        .table-cell = jobcode.level.to_s.titleize
        .table-cell.red.align-right = 'Acting' if jobcode.acting?
        .table-cell = jobcode.description

app/views/user/_manual_import_editor.html.slim
hr

h2 Manual Upload from DB2000

= form_tag import_path, multipart: true
  = FA::Icon.p('file-csv', style: :duotone, title: 'CSV files only')
  = file_field_tag :import_file, required: true
  br
  p For users not in import file:
  = switch_box(nil, :lock_missing, 'lightblue-red', 'ignore lock-missing')
  br
  = spinner_button button_text: 'Upload', css: 'big'

hr

app/views/user/_photo_editor.html.slim
hr
= render 'assign_photo', redirect_to: 'show', id: (defined?(id) ? id : nil)
hr

app/views/user/_user_actions.html.slim
- if admin
  - if locked
    = link_to(unlock_user_path(id), title: 'Unlock', class: 'unlock', method: :patch) { fa_icon('lock', fa: 'fw') }
  - elsif !is_admin
    = link_to(lock_user_path(id), title: 'Lock', class: 'lock', method: :patch) { fa_icon('unlock', fa: 'fw') }
- unless locked
  - if invited
    = link_to(invite_path(id: id), title: 'Re-send invitation', method: :put) { fa_icon('envelope-open', css: 'pending', fa: 'fw') }
  - elsif invitable
    = link_to(invite_path(id: id), title: 'Send invitation', method: :put) { fa_icon('envelope', fa: 'fw') }
  - elsif placeholder_email
    = fa_layer([{ name: 'envelope', options: { css: :gray } }, { name: 'exclamation', options: { css: :red } }], title: 'Invalid email address.')

app/views/user/_user_name.html.slim
- if name.blank?
  = email
- elsif placeholder_email
  = name
- else
  = mail_to(email, name)

app/views/user/_user_roles.html.slim
- if office.present?
  = officer_flag(office, mode: :png)
  hr
- if granted.present?
  = granted.join("<br>").html_safe
  br
- if permitted.include? :admin
  span.red All
- else
  span.red = (permitted - granted).join("<br>").html_safe

app/views/user/add_registrants.js.erb
$("#registered").html("<%= j @registered %>");
$('#additional_cert').val("");
$('#additional_email').val("");

app/views/user/cancel_registration.js.erb
<%= render 'application/update_flashes' %>

<%- if flash[:alert].blank? %>
  <%- if @cancel_link %>
    $("#register_event_<%= @registration.event.id %>").replaceWith("<%=j render('event/actions/schedule_general', event: @event) %>");
  <% end %>

  $("#registration_<%= @registration.id %>").fadeOut();
<% end %>

app/views/user/instructors.html.slim
h1 Current Instructors

= image_tag BPS::S3.new(:static).link('insignia/CI/CI.350.png'), class: 'lamp'

= form_tag do
  div
    => submit_tag 'Find Instructors', class: 'medium find-instructors'
    ' for
    = select_tag :key, options_for_select(@keys, @highlight), required: true

  = switch_box(nil, :only, 'lightblue-darkblue', 'all eligible', value: @only)

hr

#instructors.table.striped.desktop
  .table-row.header
    .table-cell Name
    .table-cell Certificate
    .table-cell title="Instructor certification expiration" ID Exp.
    - UserHelper::INSTRUCTOR_COURSES.each do |key, label|
      = instructor_header(key, @highlight, label: label)
  - @instructors.each do |user|
    - completions = user.completions.keys
    .table-row
      .table-cell = mail_to user.email, user.simple_name
      .table-cell = user.certificate
      .table-cell class=('red' if user.id_expr < Time.zone.today.end_of_year) = user.id_expr.strftime(TimeHelper::FULL_DATE)
      - UserHelper::INSTRUCTOR_COURSES.each do |key, _|
        = instructor_row(key, @highlight, completions, grade: user.grade, cpr: user.cpr_aed?)

#instructors-flex.table.striped
  - @instructors.each do |user|
    - completions = user.completions.keys
    .table-row
      .information
        .name = mail_to user.email, user.simple_name
        .certificate = user.certificate
        .expiration class=('red' if user.id_expr < Time.zone.today.end_of_year) title="Instructor certification expiration" = user.id_expr&.strftime(TimeHelper::FULL_DATE)
      .certifications.flex
        - UserHelper::INSTRUCTOR_COURSES.each do |key, label|
          - if instructor_check(key, completions, grade: user.grade, cpr: user.cpr_aed?)
            - class_list = [key, ('highlight' if instructor_highlight(key, @highlight))].compact.join(' ')
            span class=(class_list) = label == 'SN?' ? 'Exam' : label

= link_to("Email Visible Instructors (#{@instructors.count})", "mailto:#{@instructors.map(&:email).compact.uniq.join(',')}", class: 'big email-instructors')

app/views/user/request_schedule.js.erb
<%= render 'application/update_flashes' %>

<%- unless flash[:alert].present? %>
  $("#request_link_<%= @event.id %>").html("Requested").addClass("red").removeClass("blue").attr("href", "#");
<%- end %>

app/views/user/show.html.slim
h1.profile = @user.full_name

#profile
  .profile-photo = image_tag(@user.photo)

  .insignia
    .long
      p = rank_flag(@user)
      p = image_tag(BPS::S3.new(:static).link("insignia/PNG/grades/tr/#{@insignia[:grade]}.png"), title: @insignia_title[:grade], class: @insignia[:grade]) if @insignia[:grade].present?
      p = image_tag(BPS::S3.new(:static).link("insignia/PNG/membership/tr/#{@insignia[:membership]}.png"), title: @insignia_title[:membership]) if @insignia[:membership].present?
    #merit-marks title=(@insignia_title[:mm])
      - @user.mm&.times do |i|
        = image_tag(BPS::S3.new(:static).link('insignia/PNG/mm.png'))
        - if (i + 1) % 20 == 0
          br
    .pins
      = image_tag(BPS::S3.new(:static).link('insignia/CI/CI.350.png'), class: 'pin', title: 'Certified Instructor') if @user.valid_instructor?
      = image_tag(BPS::S3.new(:static).link('insignia/VE/VE.350.png'), class: 'pin', title: 'Certified Vessel Examiner') if @user.vessel_examiner?
      = membership_pin(@user.mm, @user.total_years, rank: @user.pin_rank)
    - if @user.dan_boater?
      p
        = link_to('https://www.usps.org/DANBoater/dbindex.php') do
          = image_tag(BPS::S3.new(:static).link('logos/DAN/light/DAN_Boater.png'), class: 'long light', title: 'DAN Boater Member')
          = image_tag(BPS::S3.new(:static).link('logos/DAN/dark/DAN_Boater.png'), class: 'long dark', title: 'DAN Boater Member')

  .table
    .table-row
      .table-cell.left-header Certificate
      .table-cell = @user.certificate || FA::Icon.p('question-circle', css: 'red', style: :duotone)
    .table-row
      .table-cell.left-header Email
      .table-cell = @user.email
    - if @user.phone_h.present? || mobile_phone(@user).present? || @user.phone_w.present?
      .table-row
        .table-cell.left-header Phone
        .table-cell
          - if @user.phone_h.present?
            .phone_h title="Home"
              = FA::Icon.p('house', style: :duotone, fa: :fw)
              = @user.phone_h
          - if mobile_phone(@user).present?
            .phone_c title="Mobile"
              = FA::Icon.p('mobile-alt', style: :duotone, fa: :fw)
              = mobile_phone(@user)
              - if @user.subscribe_on_register
                = FA::Icon.p('check-circle', fa: :fw, css: 'green', title: 'SMS reminders enabled')
              - else
                = FA::Icon.p('times-circle', fa: :fw, css: 'red', title: 'SMS reminders disabled by default')
          - if @user.phone_w.present?
            .phone_w title="Work"
              = FA::Icon.p('building', style: :duotone, fa: :fw)
              = @user.phone_w
    - if @user.permitted_roles.present?
      .table-row
        .table-cell.left-header Permissions
        .table-cell = role_flags(@user)
    .table-row
      .table-cell.left-header JumpStart Boat Types
      .table-cell
        - if @user.jumpstart.present?
          = @user.jumpstart
        - else
          = FA::Icon.p('do-not-enter', css: 'gray')
          span.italic None specified

= render('jobcodes', jobcodes: @user.jobcodes.current)

- if current_user.id != @user.id && current_user.permitted?(:admin, strict: true)
  h2 Actions
  ul#profile-actions.simple
    li = link_to(admin_edit_path(@user)) { FA::Icon.p('edit', style: :duotone) + 'Update user information' }

- if current_user.id == @user.id
  h2 Profile Actions
  ul#profile-actions.simple
    li = link_to(profile_edit_path) { FA::Icon.p('edit', style: :duotone) + 'Update your information' }
    - if current_user.id == @user.id && current_user.dues_due? && current_user.payable?
      li = link_to(dues_path, class: :red) { FA::Icon.p('credit-card', style: :duotone) + 'Pay your annual dues online' }
    li = link_to(user_certificate_path(@user.id), target: :_blank, class: 'green') { FA::Icon.p('file-certificate', style: :duotone) + 'View Educational Certificate' }
    li = link_to(otw_progress_path, target: :_blank, class: 'green') { FA::Icon.p('tasks', style: :duotone) + 'View BOC Progress' }

    - if current_user.any_current_tokens?
      li = link_to(profile_tokens_path) { FA::Icon.p('brackets-curly', style: :duotone) + 'Review API tokens' }

= render('registrations') if @registrations.present?

- if current_user&.permitted?(:admin) && current_user.id != @user.id
  .photo-editor = editor('photo_editor', id: @user.id)

= signal_flags(@user.full_name(html: false).sub(/1st/, '1'))

= render('corner_stripes', stripe_rank: @user.stripe_rank, first_stripe_class: @user.first_stripe_class)