config/routes.rb
# frozen_string_literal: true

require 'sidekiq/web'

Rails.application.routes.draw do
  root 'public#home'

  devise_for(
    :users,
    path: '',
    path_names: {
      sign_in: 'login',
      sign_out: 'logout',
      new_user_password: 'reset'
    },
    controllers: {
      registrations: 'users/registrations',
      sessions: 'users/sessions',
      invitations: 'users/invitations'
    }
  )

  devise_scope :user do
    get    '/users/:id/edit',     to: 'users/registrations#admin_edit',   as: 'admin_edit'
    put    '/users/:id',          to: 'users/registrations#admin_update', as: 'admin_update'
  end

  authenticate :user, lambda { |u| u.permitted?(:admin, strict: true) } do
    mount Sidekiq::Web => '/sidekiq'
  end

  ### Short URLs
  get     '/e/:slug',         to: 'events/events#slug',         as: 'event_slug'
  get     '/a/:id',           to: 'public#announcement_direct', as: 'short_announcement'
  get     '/b/:year/:month',  to: 'public#bilge',               as: 'short_bilge'
  get     '/m/:year/:month',  to: 'members#find_minutes',       as: 'short_minutes'
  get     '/ex/:year/:month', to: 'members#find_minutes',       as: 'short_excom', defaults: { minutes_excom: true }

  ### Profile management
  as :user do
    get    '/profile',            to: 'user#show'
    get    '/profile/edit',       to: 'users/registrations#edit'
    put    '/profile/edit',       to: 'users/registrations#update'
    get    '/reset',              to: 'devise/passwords#new'

    get    '/profile/tokens',     to: 'user#tokens'
    delete '/profile/tokens/:id', to: 'user#revoke_token', as: 'revoke_token'
  end

  ### Markdown pages
  %i[
    home about join requirements vsc education calendar civic history links
    members welcome user_help
  ].each do |md|
    get   "/#{md}",      to: "public##{md}", as: md,    defaults: { page_name: md } unless md.in?(%i[home members user_help welcome])
    get   "/#{md}/edit", to: 'members#edit_markdown',   defaults: { page_name: md }
    patch "/#{md}/edit", to: 'members#update_markdown', defaults: { page_name: md }
  end

  get     '/home',            to: redirect('/')
  get     '/members',         to: 'members#members'
  get     '/user_help',       to: 'members#user_help'
  get     '/welcome',         to: 'members#welcome'
  get     '/edit/:page_name', to: 'members#edit_markdown',   as: 'edit_page'
  patch   '/edit/:page_name', to: 'members#update_markdown', as: 'update_page'

  ### Static pages
  get     '/refunds',        to: 'braintree#refunds'
  get     '/payment_terms',  to: 'braintree#terms'
  get     '/flags',          to: 'flags#flags'
  get     '/flags/national', to: 'flags#national'
  get     '/tridents',       to: 'flags#tridents'
  get     '/intersections',  to: 'flags#intersections'
  get     '/signals',        to: 'flags#signals'
  get     '/complete',       to: 'public#complete'
  get     '/cancelled',      to: 'public#cancelled'

  ### Pre-loaded pages
  get     '/ranks',            to: 'members#ranks'
  get     '/auto_permissions', to: 'permissions#auto'

  ### Functional pages
  get     '/bridge', to: 'bridge#list'
  get     '/store',  to: 'public#store'

  # Photo gallery
  get     '/photos',       to: 'gallery#index'
  post    '/assign_photo', to: 'user#assign_photo'

  # Membership
  get     '/apply',        to: 'member_applications#new'
  get     '/applications', to: 'member_applications#review'
  get     '/dues',         to: 'members#dues'
  get     '/glyc_members', to: 'members#glyc_members'
  post    '/glyc_members', to: 'members#update_glyc_members'

  # Float plans
  resources :float_plans, only: %i[index show new create] do
    patch :refresh, on: :member
  end

  # Admin utilities
  namespace :admin do
    # S3 Link Generator
    get    '/s3',                        to: 'links#s3'
    post   '/s3',                        to: 'links#s3'

    # Versions
    get    '/versions/:model/:id',       to: 'versions#show',   as: 'show_versions'
    get    '/versions/:model/:id/:a/:b', to: 'versions#diff',   as: 'diff_versions'
    post   '/versions/:model/:id/:a/:b', to: 'versions#diff'
    patch  '/versions/:model/:id/:a',    to: 'versions#revert', as: 'revert_version'
    get    '/versions(/:model)',         to: 'versions#index',  as: 'versions'

    # Logo Generator
    get    '/logo',                      to: 'logos#logo'

    # Promo Codes
    get    '/promo_codes',               to: 'promo_codes#list'
    get    '/promo_codes/new',           to: 'promo_codes#new',      as: 'new_promo_code'
    put    '/promo_codes/new',           to: 'promo_codes#create',   as: 'create_promo_code'
    patch  '/promo_codes/:id/activate',  to: 'promo_codes#activate', as: 'activate_promo_code'
    delete '/promo_codes/:id/expire',    to: 'promo_codes#expire',   as: 'expire_promo_code'

    # Send Message
    resources :messages, only: %i[new create]
    resources :emails, only: %i[new create]

    # Generic Payments
    get    '/generic_payments',          to: 'generic_payments#index'
    get    '/generic_payments/new',      to: 'generic_payments#new'
    post   '/generic_payments',          to: 'generic_payments#create'

    # Import Logs
    resources :import_logs, only: %i[index show]

    # DMARC Reports
    resources :dmarc_reports, only: %i[index show create]

    # Placecards
    resources :placecards, only: %i[new create]
  end

  # Newsletter
  get     '/newsletter',         to: 'public#newsletter'
  get     '/bilge/:year/:month', to: 'public#bilge',         as: 'bilge'
  post    '/bilge',              to: 'members#upload_bilge', as: 'upload_bilge'
  get     '/bilge(/:year)',      to: redirect('/newsletter')

  # Announcements
  get     '/announcement/:id',        to: 'public#announcement_direct',  as: 'announcement'
  post    '/announcement',            to: 'members#upload_announcement', as: 'upload_announcement'
  patch   '/announcement/:id/hide',   to: 'members#hide_announcement',   as: 'hide_announcement'
  patch   '/announcement/:id/unhide', to: 'members#unhide_announcement', as: 'unhide_announcement'
  delete  '/announcement/:id',        to: 'members#remove_announcement', as: 'remove_announcement'
  get     '/announcement',            to: redirect('/newsletter')
  get     '/announcements',           to: redirect('/newsletter')

  # Minutes
  get     '/minutes',              to: 'members#minutes'
  post    '/minutes',              to: 'members#upload_minutes', as: 'upload_minutes'
  get     '/minutes/:year/:month', to: 'members#find_minutes',   as: 'get_minutes'
  get     '/excom/:year/:month',   to: 'members#find_minutes',   as: 'get_minutes_excom', defaults: { excom: 'true' }
  get     '/minutes(/:year)', to: redirect('/minutes')

  # Registration
  put     '/register',        to: 'public#register', as: 'public_register'
  post    '/register',        to: 'public#register', as: 'long_register'

  # Subscriptions
  post    '/subscribe/:id',   to: 'members#subscribe',   as: 'subscribe'
  post    '/unsubscribe/:id', to: 'members#unsubscribe', as: 'unsubscribe'

  # User invitation
  put     '/invite/:id', to: 'user#invite', as: 'invite'
  put     '/invite_all', to: 'user#invite_all'

  # Markdown files and header images
  get     '/file',               to: 'file#new',            as: 'file'
  post    '/file/upload',        to: 'file#create',         as: 'upload_file'
  delete  '/file/:id/destroy',   to: 'file#destroy',        as: 'remove_file'
  get     '/header',             to: 'file#new_header',     as: 'header'
  post    '/header/upload',      to: 'file#create_header',  as: 'upload_header'
  delete  '/header/:id/destroy', to: 'file#destroy_header', as: 'remove_header'

  # Locations and Event Types
  %i[location event_type].each do |model|
    get     "/#{model}s",               to: "#{model}s#list",    as: "#{model}s"
    get     "/#{model}s/new",           to: "#{model}s#new",     as: "new_#{model}"
    post    "/#{model}s/create",        to: "#{model}s#create",  as: "create_#{model}"
    get     "/#{model}s/:id/edit",      to: "#{model}s#edit",    as: "edit_#{model}"
    patch   "/#{model}s/:id/update",    to: "#{model}s#update",  as: "update_#{model}"
    delete  "/#{model}s/:id/remove",    to: "#{model}s#remove",  as: "remove_#{model}"
    get     "/#{model}s/refresh(/:id)", to: "#{model}s#refresh", as: "refresh_#{model}s"
  end

  # Roster Historical Records
  namespace :roster do
    resource :award_recipients
    resource :past_commanders
    resource :archive_files
  end

  # Photo Galleries
  post    '/album/new',       to: 'gallery#add_album',    as: 'new_album'
  get     '/album/:id',       to: 'gallery#show',         as: 'show_album'
  delete  '/album/:id',       to: 'gallery#remove_album', as: 'remove_album'
  post    '/album/photo',     to: 'gallery#upload_photo', as: 'upload_photo'
  delete  '/album/photo/:id', to: 'gallery#remove_photo', as: 'remove_photo'

  # Editor auto-show state setters
  post    '/auto_show', to: 'user#auto_show', as: 'auto_show'
  post    '/auto_hide', to: 'user#auto_hide', as: 'auto_hide'

  # Member Applications
  put     '/apply',                   to: 'member_applications#apply',   as: 'submit_application'
  get     '/applied(/:token)',        to: 'member_applications#applied', as: 'applied'
  patch   '/approve_application/:id', to: 'member_applications#approve', as: 'approve_application'

  # Roster
  get     '/roster',                    to: 'members#roster',        as: 'roster'
  # get  '/update_roster',             to: 'members#update_roster', as: 'update_roster'
  # post '/update_roster',             to: 'members#upload_roster'
  get     '/roster/gen(/:orientation)', to: 'members#roster_gen',    as: 'roster_gen', defaults: { orientation: 'detailed' }

  # OTW Trainings
  get     '/otw',                to: 'otw_trainings#user'
  get     '/otw/progress(/:id)', to: 'otw_trainings#user_progress', as: 'otw_progress'
  get     '/otw/requests',       to: 'otw_trainings#list_requests'

app/controllers/gallery_controller.rb
# frozen_string_literal: true

class GalleryController < ApplicationController
  secure!(:photos, except: %i[index show])

  title!('Photos')

  def index
    @albums = Album.includes(:photos).order(created_at: :desc).all
    @album = Album.new
    @photo = Photo.new
  end

  def add_album
    return remove_album if clean_params[:remove].present?

    @album = Album.new(album_params)
    if @album.save
      redirect_to photos_path, success: 'Successfully added album!'
    else
      failed_to_save
    end
  end

  def show
    @album = Album.find_by(id: clean_params[:id])
    @photo = Photo.new
    return if @album.present?

    flash[:alert] = 'Album not found.'
    redirect_to photos_path
  end

  def upload_photo
    Photo.transaction do
      photo_params[:photo_file].each { |photo| process_photo_upload(photo) }
    end

    upload_flashes
    upload_redirect
  end

  def remove_photo
    photo = Photo.find_by(id: clean_params[:id])
    album_id = photo.album_id

    if photo.destroy
      flash[:success] = 'Successfully removed photo!'
    else
      flash[:alert] = 'There was a problem removing the photo.'
    end

    redirect_to show_album_path(album_id)
  end

  def remove_album
    if album&.destroy
      redirect_to photos_path, success: 'Successfully removed album!'
    else
      redirect_to photos_path, alert: 'There was a problem removing the album.'
    end
  end

private

  def album_params
    params.require(:album).permit(:name)
  end

  def photo_params
    params.require(:photo).permit(:album_id, photo_file: [])
  end

  def clean_params
    params.permit(:id, :remove, :redirect_to_album)
  end

  def album
    @album = Album.find_by(
      params[:album].present? ? album_params : { id: clean_params[:id] }
    )
  end

  def process_photo_upload(photo_file)
    photo_attributes = photo_params.to_hash.merge('photo_file' => photo_file)
    photo = Photo.new(photo_attributes)
    photo.valid? ? photo.save! : @failed = true
    raise ActiveRecord::Rollback if @failed
  end

  def upload_flashes
    if @failed
      flash[:alert] = 'There was a problem creating the photo.'
    else
      flash[:success] = 'Successfully added photo!'
    end
  end

  def upload_redirect
    if clean_params[:redirect_to_album].present?
      redirect_to show_album_path(photo_params[:album_id])
    else
      redirect_to photos_path
    end
  end

  def failed_to_save
    errors = @album.errors.full_messages
    flash[:alert] = 'There was a problem creating the album.'
    flash[:error] = errors
    redirect_to photos_path
  end
end

app/views/gallery/_add_album_form.html.slim
#add-album
  = form_for(@album, url: new_album_path, multipart: true) do |f|
    = f.text_field :name, required: true, placeholder: 'Enter album name'
    br
    label.switch
      = check_box_tag :remove, class: "slider round"
      span.slider.round
        .description.create
    br
    = spinner_button(button_text: "Submit", css_class: 'big')

app/views/gallery/_album.html.slim
- @album.photos.each do |photo|
  a data-fancybox="album_#{@album.id}" href=(BPS::S3.new(:photos).link(photo.photo_file.path))
    = image_tag BPS::S3.new(:photos).link(photo.photo_file.path(:thumb))

app/views/gallery/_album_editor.html.slim
#upload-photo
  = render 'upload_photos'
  hr
  = link_to 'Remove album', remove_album_path(@album), method: :delete, class: 'red', data: {confirm: 'Are you sure you want to remove this album and all of its photos?'}
  hr

app/views/gallery/_cover.html.slim
- if album.photos.present?
  = link_to(show_album_path(album)) do
    = image_tag BPS::S3.new(:photos).link(album.cover.photo_file.path(:medium))
- else
  h3.red This album has no photos.

app/views/gallery/_edit_album.html.slim
.table.striped.photos
  .table-row.header
    .table-cell Photo
    .table-cell
  - @album.photos.each do |photo|
    .table-row
      .table-cell = image_tag BPS::S3.new(:photos).link(photo.photo_file.path(:thumb))
      .table-cell
        = link_to(remove_photo_path(id: photo.id), method: :delete, data: {confirm: 'Are you sure you want to remove this photo from the album?'}) { FA::Icon.p('minus-square', style: :duotone, css: 'red') }
        | Uploaded on #{photo.created_at.strftime(TimeHelper::MEDIUM_TIME_FORMAT)}

app/views/gallery/_gallery_editor.html.slim
#add-album
  hr
  h2 Create or remove an album
  = form_for(@album, url: new_album_path, multipart: true) do |f|
    = f.text_field :name, required: true, placeholder: 'Enter album name'
    br
    = switch_box(nil, :remove, 'lightblue-red', 'create remove')
    br
    = spinner_button(button_text: "Submit", css: 'big')
  = render 'upload_photos'
  hr

app/views/gallery/_upload_photos.html.slim
hr
h2 Upload photos
= form_for(@photo, url: upload_photo_path, multipart: true) do |f|
  - if controller.action_name == 'show'
    = hidden_field_tag :redirect_to_album, true
    = f.hidden_field :album_id, value: @album.id
  - else
    = f.select :album_id, options_for_select(@albums.map { |a| [a.name, a.id] }), include_blank: true, required: true, prompt: "Please select an album"
    br
  = FA::Icon.p('file-image', style: :duotone, css: 'file-type')
  = f.file_field :photo_file, required: true, multiple: true
  br
  = spinner_button(button_text: "Submit", css: 'big')
  br
  small The first photo in an album will be displayed on the gallery page.

app/views/gallery/index.html.slim
h1 Squadron Photos

- if current_user&.permitted?(:photos)
  = editor('gallery_editor')

- if @albums.blank?
  h2 We're sorry, but there are currently no photo albums available.
  p Please check back again later!
- else
  - @albums.each do |album|
    h2 = album.name.titleize
    = render 'cover', album: album
    hr

app/views/gallery/show.html.slim
h1 = @album.name.titleize

= editor('album_editor') if current_user&.permitted?(:photos)

- if @album.photos.present?
  - if current_user&.permitted?(:photos)
    = render 'edit_album'
  - else
    = render 'album'
- else
  h3 There are no photos in this album.