config/routes.rb
# frozen_string_literal: true

require 'sidekiq/web'

Rails.application.routes.draw do
  root 'public#home'

  devise_for(
    :users,
    path: '',
    path_names: {
      sign_in: 'login',
      sign_out: 'logout',
      new_user_password: 'reset'
    },
    controllers: {
      registrations: 'users/registrations',
      sessions: 'users/sessions',
      invitations: 'users/invitations'
    }
  )

  devise_scope :user do
    get    '/users/:id/edit',     to: 'users/registrations#admin_edit',   as: 'admin_edit'
    put    '/users/:id',          to: 'users/registrations#admin_update', as: 'admin_update'
  end

  authenticate :user, lambda { |u| u.permitted?(:admin, strict: true) } do
    mount Sidekiq::Web => '/sidekiq'
  end

  ### Short URLs
  get     '/e/:slug',         to: 'events/events#slug',         as: 'event_slug'
  get     '/a/:id',           to: 'public#announcement_direct', as: 'short_announcement'
  get     '/b/:year/:month',  to: 'public#bilge',               as: 'short_bilge'
  get     '/m/:year/:month',  to: 'members#find_minutes',       as: 'short_minutes'
  get     '/ex/:year/:month', to: 'members#find_minutes',       as: 'short_excom', defaults: { minutes_excom: true }

  ### Profile management
  as :user do
    get    '/profile',            to: 'user#show'
    get    '/profile/edit',       to: 'users/registrations#edit'
    put    '/profile/edit',       to: 'users/registrations#update'
    get    '/reset',              to: 'devise/passwords#new'

    get    '/profile/tokens',     to: 'user#tokens'
    delete '/profile/tokens/:id', to: 'user#revoke_token', as: 'revoke_token'
  end

  ### Markdown pages
  %i[
    home about join requirements vsc education calendar civic history links
    members welcome user_help
  ].each do |md|
    get   "/#{md}",      to: "public##{md}", as: md,    defaults: { page_name: md } unless md.in?(%i[home members user_help welcome])
    get   "/#{md}/edit", to: 'members#edit_markdown',   defaults: { page_name: md }
    patch "/#{md}/edit", to: 'members#update_markdown', defaults: { page_name: md }
  end

  get     '/home',            to: redirect('/')
  get     '/members',         to: 'members#members'
  get     '/user_help',       to: 'members#user_help'
  get     '/welcome',         to: 'members#welcome'
  get     '/edit/:page_name', to: 'members#edit_markdown',   as: 'edit_page'
  patch   '/edit/:page_name', to: 'members#update_markdown', as: 'update_page'

  ### Static pages
  get     '/refunds',        to: 'braintree#refunds'
  get     '/payment_terms',  to: 'braintree#terms'
  get     '/flags',          to: 'flags#flags'
  get     '/flags/national', to: 'flags#national'
  get     '/tridents',       to: 'flags#tridents'
  get     '/intersections',  to: 'flags#intersections'
  get     '/signals',        to: 'flags#signals'
  get     '/complete',       to: 'public#complete'
  get     '/cancelled',      to: 'public#cancelled'

  ### Pre-loaded pages
  get     '/ranks',            to: 'members#ranks'
  get     '/auto_permissions', to: 'permissions#auto'

  ### Functional pages
  get     '/bridge', to: 'bridge#list'
  get     '/store',  to: 'public#store'

  # Photo gallery
  get     '/photos',       to: 'gallery#index'
  post    '/assign_photo', to: 'user#assign_photo'

  # Membership
  get     '/apply',        to: 'member_applications#new'
  get     '/applications', to: 'member_applications#review'
  get     '/dues',         to: 'members#dues'
  get     '/glyc_members', to: 'members#glyc_members'
  post    '/glyc_members', to: 'members#update_glyc_members'

  # Float plans
  resources :float_plans, only: %i[index show new create] do
    patch :refresh, on: :member
  end

  # Admin utilities
  namespace :admin do
    # S3 Link Generator
    get    '/s3',                        to: 'links#s3'
    post   '/s3',                        to: 'links#s3'

    # Versions
    get    '/versions/:model/:id',       to: 'versions#show',   as: 'show_versions'
    get    '/versions/:model/:id/:a/:b', to: 'versions#diff',   as: 'diff_versions'
    post   '/versions/:model/:id/:a/:b', to: 'versions#diff'
    patch  '/versions/:model/:id/:a',    to: 'versions#revert', as: 'revert_version'
    get    '/versions(/:model)',         to: 'versions#index',  as: 'versions'

    # Logo Generator
    get    '/logo',                      to: 'logos#logo'

    # Promo Codes
    get    '/promo_codes',               to: 'promo_codes#list'
    get    '/promo_codes/new',           to: 'promo_codes#new',      as: 'new_promo_code'
    put    '/promo_codes/new',           to: 'promo_codes#create',   as: 'create_promo_code'
    patch  '/promo_codes/:id/activate',  to: 'promo_codes#activate', as: 'activate_promo_code'
    delete '/promo_codes/:id/expire',    to: 'promo_codes#expire',   as: 'expire_promo_code'

    # Send Message
    resources :messages, only: %i[new create]
    resources :emails, only: %i[new create]

    # Generic Payments
    get    '/generic_payments',          to: 'generic_payments#index'
    get    '/generic_payments/new',      to: 'generic_payments#new'
    post   '/generic_payments',          to: 'generic_payments#create'

    # Import Logs
    resources :import_logs, only: %i[index show]

    # DMARC Reports
    resources :dmarc_reports, only: %i[index show create]

    # Placecards
    resources :placecards, only: %i[new create]
  end

  # Newsletter
  get     '/newsletter',         to: 'public#newsletter'
  get     '/bilge/:year/:month', to: 'public#bilge',         as: 'bilge'
  post    '/bilge',              to: 'members#upload_bilge', as: 'upload_bilge'
  get     '/bilge(/:year)',      to: redirect('/newsletter')

  # Announcements
  get     '/announcement/:id',        to: 'public#announcement_direct',  as: 'announcement'
  post    '/announcement',            to: 'members#upload_announcement', as: 'upload_announcement'
  patch   '/announcement/:id/hide',   to: 'members#hide_announcement',   as: 'hide_announcement'
  patch   '/announcement/:id/unhide', to: 'members#unhide_announcement', as: 'unhide_announcement'
  delete  '/announcement/:id',        to: 'members#remove_announcement', as: 'remove_announcement'
  get     '/announcement',            to: redirect('/newsletter')
  get     '/announcements',           to: redirect('/newsletter')

  # Minutes
  get     '/minutes',              to: 'members#minutes'
  post    '/minutes',              to: 'members#upload_minutes', as: 'upload_minutes'
  get     '/minutes/:year/:month', to: 'members#find_minutes',   as: 'get_minutes'
  get     '/excom/:year/:month',   to: 'members#find_minutes',   as: 'get_minutes_excom', defaults: { excom: 'true' }
  get     '/minutes(/:year)', to: redirect('/minutes')

  # Registration
  put     '/register',        to: 'public#register', as: 'public_register'
  post    '/register',        to: 'public#register', as: 'long_register'

  # Subscriptions
  post    '/subscribe/:id',   to: 'members#subscribe',   as: 'subscribe'
  post    '/unsubscribe/:id', to: 'members#unsubscribe', as: 'unsubscribe'

  # User invitation
  put     '/invite/:id', to: 'user#invite', as: 'invite'
  put     '/invite_all', to: 'user#invite_all'

  # Markdown files and header images
  get     '/file',               to: 'file#new',            as: 'file'
  post    '/file/upload',        to: 'file#create',         as: 'upload_file'
  delete  '/file/:id/destroy',   to: 'file#destroy',        as: 'remove_file'
  get     '/header',             to: 'file#new_header',     as: 'header'
  post    '/header/upload',      to: 'file#create_header',  as: 'upload_header'
  delete  '/header/:id/destroy', to: 'file#destroy_header', as: 'remove_header'

  # Locations and Event Types
  %i[location event_type].each do |model|
    get     "/#{model}s",               to: "#{model}s#list",    as: "#{model}s"
    get     "/#{model}s/new",           to: "#{model}s#new",     as: "new_#{model}"
    post    "/#{model}s/create",        to: "#{model}s#create",  as: "create_#{model}"
    get     "/#{model}s/:id/edit",      to: "#{model}s#edit",    as: "edit_#{model}"
    patch   "/#{model}s/:id/update",    to: "#{model}s#update",  as: "update_#{model}"
    delete  "/#{model}s/:id/remove",    to: "#{model}s#remove",  as: "remove_#{model}"
    get     "/#{model}s/refresh(/:id)", to: "#{model}s#refresh", as: "refresh_#{model}s"
  end

  # Roster Historical Records
  namespace :roster do
    resource :award_recipients
    resource :past_commanders
    resource :archive_files
  end

  # Photo Galleries
  post    '/album/new',       to: 'gallery#add_album',    as: 'new_album'
  get     '/album/:id',       to: 'gallery#show',         as: 'show_album'
  delete  '/album/:id',       to: 'gallery#remove_album', as: 'remove_album'
  post    '/album/photo',     to: 'gallery#upload_photo', as: 'upload_photo'
  delete  '/album/photo/:id', to: 'gallery#remove_photo', as: 'remove_photo'

  # Editor auto-show state setters
  post    '/auto_show', to: 'user#auto_show', as: 'auto_show'
  post    '/auto_hide', to: 'user#auto_hide', as: 'auto_hide'

  # Member Applications
  put     '/apply',                   to: 'member_applications#apply',   as: 'submit_application'
  get     '/applied(/:token)',        to: 'member_applications#applied', as: 'applied'
  patch   '/approve_application/:id', to: 'member_applications#approve', as: 'approve_application'

  # Roster
  get     '/roster',                    to: 'members#roster',        as: 'roster'
  # get  '/update_roster',             to: 'members#update_roster', as: 'update_roster'
  # post '/update_roster',             to: 'members#upload_roster'
  get     '/roster/gen(/:orientation)', to: 'members#roster_gen',    as: 'roster_gen', defaults: { orientation: 'detailed' }

  # OTW Trainings
  get     '/otw',                to: 'otw_trainings#user'
  get     '/otw/progress(/:id)', to: 'otw_trainings#user_progress', as: 'otw_progress'
  get     '/otw/requests',       to: 'otw_trainings#list_requests'

app/models/member_application.rb
# frozen_string_literal: true

class MemberApplication < ApplicationRecord
  payable
  has_many :member_applicants
  accepts_nested_attributes_for :member_applicants

  has_one :approver, class_name: 'User'

  validates :member_applicants, presence: true

  scope :pending, -> { where(approved_at: nil).includes(:member_applicants) }

  def primary
    member_applicants.select(&:primary).first
  end

  def additional
    member_applicants.reject(&:primary)
  end

  def payment_amount
    return (139 + additional.count) if additional.present?
    return 12 if primary.member_type == 'Apprentice'

    93
  end

  def approve!(approving_user)
    return { requires: :excom } unless approving_user.excom?

    update(approved_at: Time.zone.now, approver_id: approving_user.id)

    parent = create_primary_user(primary)
    users = [parent]

    additional&.each do |member|
      users << User.create!(user_hash(member).merge(parent_id: parent.id))
    end

    send_approval_notices(users)
  end

private

  def user_hash(applicant)
    {
      certificate: SecureRandom.hex(8),
      first_name: applicant.first_name,
      last_name: applicant.last_name,
      email: applicant.email,
      password: SecureRandom.hex(32)
    }
  end

  def create_primary_user(primary)
    User.create!(
      user_hash(primary).merge(
        address_1: primary.address_1,
        address_2: primary.address_2,
        city: primary.city,
        state: primary.state,
        zip: primary.zip
      )
    )
  end

  def send_approval_notices(users)
    MemberApplicationMailer.approved(self).deliver
    MemberApplicationMailer.approval_notice(self).deliver
    users.map(&:invite!)
  end
end

app/controllers/member_applications_controller.rb
# frozen_string_literal: true

class MemberApplicationsController < ApplicationController
  include BraintreeHelper

  secure!(:excom, only: %i[review approve])

  title!('Become a Member!')

  before_action :load_payment, only: :applied
  before_action :process_application, only: :apply

  def new
    @member_application = MemberApplication.new
    @member_application_person = MemberApplicant.new(
      member_application: @member_application
    )

    @member_application_persons = [@member_application_person]
  end

  def apply
    if @member_application.persisted?
      confirm_applied_path = applied_path(
        token: @member_application.payment.token
      )
      MemberApplicationMailer.confirm(@member_application).deliver
      render js: "window.location = '#{confirm_applied_path}'"
    else
      flash.now[:alert] = 'There was a problem with your application.'
    end
  end

  def applied
    transaction_details
    @purchase_info[:registered] = @payment.parent.member_applicants

    @client_token = Payment.client_token(user_id: current_user&.id)
    @receipt = @payment.parent.primary.email
    @address = BridgeOffice.includes(:user).find_by(office: :treasurer).user.mailing_address
  end

  def review
    @applications = MemberApplication.pending
  end

  def approve
    @member_application = MemberApplication.find_by(id: approve_params[:id])

    if @member_application.approve!(current_user) == { requires: :excom }
      flash.now[:alert] = 'Only ExCom members can approve applications.'
      render 'applicaiton/update_flashes'
    end

    flash.now[:success] = 'Successfully approved application and invited new members!'
  end

private

  def primary_member_params
    params.permit(
      %i[
        first_name middle_name last_name dob gender
        address_1 address_2 city state zip email phone_h phone_c phone_w fax
        boat_type boat_length boat_name sig_other_name previous_certificate
      ]
    )
  end

  def additional_member_params
    params.permit(
      member_application: {
        member_applicants_attributes: %i[
          primary first_name middle_name last_name dob gender
          address_1 address_2 city state zip phone_h phone_c
          phone_w fax email sea_scout sig_other_name boat_type
          boat_length boat_name previous_certificate _destroy
        ]
      }
    )
  end

  def applied_params
    params.permit(:token)
  end

  def approve_params
    params.permit(:id)
  end

  def load_payment
    @token = applied_params[:token]
    @payment = Payment.find_by(token: @token)
  end

  def process_application
    MemberApplication.transaction do
      create_application
    end
  rescue ActiveRecord::RecordInvalid => e
    failed_application(e)
  end

  def create_application
    @member_application = MemberApplication.new
    people = applicants['member_applicants_attributes'].first.map do |a|
      person = MemberApplicant.new(a.merge(member_application: @member_application))
      @member_application.member_applicants << person
    end
    @member_application_persons = [people]

    raise 'Failed reCAPTCHA' unless verify_recaptcha(model: @member_application)

    @member_application.save!
  end

  def failed_application(e)
    flash.now[:error] = e.message.gsub('Member applicants base ', '')
                         .gsub('Validation failed: ', '')
  end

  def applicants
    return applicant_attributes_hash([primary_applicant]) if additionals.blank?

    applicant_attributes_hash(with_additionals)
  end

  def applicant_attributes_hash(*applicants)
    { 'member_applicants_attributes' => applicants }
  end

  def primary_applicant
    primary_member_params.to_h.merge(
      primary: true, member_application: @member_application
    )
  end

  def with_additionals
    adds = additionals.reduce({}, :merge).values.reject do |a|
      a == true || a.is_a?(MemberApplication) || a.key?('_destroy')
    end

    adds.each do |a|
      a[:member_application] = @member_application
      a[:primary] = false
    end

    [primary_applicant, adds].compact.flatten
  end

  def additionals
    @additionals ||= additional_member_params.values.map(&:to_h).map(&:values).flatten
  end
end

app/views/member_applications/_additional_applicant.html.slim
h2 Additional Household Applicant
= ff.hidden_field 'member_type', value: 'Family'

.applicant-section-title Personal Info

.left
  span.red = FA::Icon.p('dot-circle', style: :duotone, css: 'red', shrink: 4)
  = ff.label 'first_name', 'First name'
.right = ff.text_field 'first_name', required: true
br.clear

.left = ff.label 'middle_name', 'Middle name'
.right = ff.text_field 'middle_name'
br.clear

.left
  span.red = FA::Icon.p('dot-circle', style: :duotone, css: 'red', shrink: 4)
  = ff.label 'last_name', 'Last name'
.right = ff.text_field 'last_name', required: true
br.clear

.left
  = ff.label 'dob', 'Date of Birth'
  ul: li Your date of birth will not be displayed anywhere.
.right = ff.date_field 'dob', class: 'date'
br.clear

.left = ff.label 'gender', 'Gender'
.right = ff.select 'gender', options_for_select(['Male', 'Female', 'Prefer not to say']), include_blank: true
br.clear

.left
  .applicant-section-title Contact Info

  .left
    span.red = FA::Icon.p('dot-circle', style: :duotone, css: 'red', shrink: 4)
    = ff.label 'email', 'Email'
  .right = ff.email_field 'email', required: true
  br.clear

.right
  .applicant-section-title Additional Info

  .left = ff.label 'sea_scout', 'Sea Scout?'
  .right = ff.check_box 'sea_scout'
  br.clear

  .left = ff.label 'sig_other_name', "Significant other's name"
  .right = ff.text_field 'sig_other_name'
  br.clear

  .left
    = ff.label 'previous_certificate', 'Previous USPS Certificate'
    ul: li If you have ever been a member of USPS in the past, enter your prior certificate number here.
  .right = ff.text_field 'previous_certificate', maxlength: 7
  br.clear
br.clear
= ff.remove_nested_fields_link 'Remove this person from this application', data: { confirm: 'Are you sure you want to remove this person from the application?' }, class: 'red'

app/views/member_applications/_primary_applicant.html.slim
h2 Primary Applicant

.applicant-section-title Personal Info

.left
  span.red = FA::Icon.p('dot-circle', style: :duotone, css: 'red', shrink: 4)
  = label_tag 'first_name', 'First name'
.right = text_field_tag 'first_name', '', required: true
br.clear

.left = label_tag 'middle_name', 'Middle name'
.right = text_field_tag 'middle_name'
br.clear

.left
  span.red = FA::Icon.p('dot-circle', style: :duotone, css: 'red', shrink: 4)
  = label_tag 'last_name', 'Last name'
.right = text_field_tag 'last_name', '', required: true
br.clear

.left
  = label_tag 'dob', 'Date of Birth'
  ul: li Your date of birth will not be displayed anywhere.
.right = date_field_tag 'dob', '', class: 'date'
br.clear

.left = label_tag 'gender', 'Gender'
.right = select_tag 'gender', options_for_select(['Male', 'Female', 'Prefer not to say']), include_blank: true
br.clear

.left
  .applicant-section-title Address

  .left
    span.red = FA::Icon.p('dot-circle', style: :duotone, css: 'red', shrink: 4)
    = label_tag 'address_1', 'Address'
  .right = text_field_tag 'address_1', '', required: true
  br.clear

  .left
  .right = text_field_tag 'address_2'
  br.clear

  .left
    span.red = FA::Icon.p('dot-circle', style: :duotone, css: 'red', shrink: 4)
    = label_tag 'city', 'City'
  .right = text_field_tag 'city', '', required: true
  br.clear

  .left
    span.red = FA::Icon.p('dot-circle', style: :duotone, css: 'red', shrink: 4)
    = label_tag 'state', 'State / Province'
  .right = text_field_tag 'state', '', required: true
  br.clear

  .left
    span.red = FA::Icon.p('dot-circle', style: :duotone, css: 'red', shrink: 4)
    = label_tag 'zip', 'ZIP / Postal Code'
  .right = text_field_tag 'zip', '', required: true, maxlength: 10
  br.clear

.right
  .applicant-section-title Contact Info

  .left
    span.red = FA::Icon.p('dot-circle', style: :duotone, css: 'red', shrink: 4)
    = label_tag 'email', 'Email'
  .right = email_field_tag 'email', '', required: true
  br.clear

  .left
    span.red = FA::Icon.p('dot-circle', style: :duotone, css: 'red', shrink: 4)
    = label_tag 'phone_h', 'Phone: home'
  .right = text_field_tag 'phone_h'
  br.clear

  .left = label_tag 'phone_c', 'cell'
  .right = text_field_tag 'phone_c'
  br.clear

  .left = label_tag 'phone_w', 'work'
  .right = text_field_tag 'phone_w'
  br.clear

  .left = label_tag 'fax', 'Fax'
  .right = text_field_tag 'fax'
  br.clear
br.clear

.left
  .applicant-section-title Boat Info

  .left
    span.red = FA::Icon.p('dot-circle', style: :duotone, css: 'red', shrink: 4)
    = label_tag 'boat_type', 'Boat type'
  .right = select_tag 'boat_type', options_for_select(%w[Power Sail Paddle Other Multiple None]), include_blank: true, required: true
  br.clear

  .left = label_tag 'boat_lentgh', 'Boat length'
  .right
    = number_field_tag 'boat_length', '', class: 'number'
    | feet
  br.clear

  .left = label_tag 'boat_name', 'Boat name'
  .right = text_field_tag 'boat_name'
  br.clear

.right
  .applicant-section-title Additional Info

  .left = label_tag 'sea_scout', 'Sea Scout?'
  .right = check_box_tag 'sea_scout'
  br.clear

  .left = label_tag 'sig_other_name', "Significant other's name"
  .right = text_field_tag 'sig_other_name'
  br.clear

  .left
    = label_tag 'previous_certificate', 'Previous USPS Certificate'
    ul: li If you have ever been a member of USPS in the past, enter your prior certificate number here.
  .right = text_field_tag 'previous_certificate', '', maxlength: 7
  br.clear
br.clear

app/views/member_applications/_review_applicant.html.slim
.table-row
  .table-cell = tag(:hr)
  .table-cell = tag(:hr)

.table-row class=(css if defined?(css))
  .table-cell.bold Name:
  .table-cell = "#{applicant.first_name} #{applicant.middle_name} #{applicant.last_name}"

.table-row class=(css if defined?(css))
  .table-cell.bold Email:
  .table-cell = applicant.email

.table-row class=(css if defined?(css))
  .table-cell.bold DOB:
  .table-cell = applicant.dob

.table-row class=(css if defined?(css))
  .table-cell.bold Gender:
  .table-cell = applicant.gender

- if applicant.primary
  .table-row class=(css if defined?(css))
    .table-cell.bold Address:
    .table-cell
      = applicant.address_1
      - if applicant.address_2.present?
        br
        = applicant.address_2
      br
      = "#{applicant.city}, #{applicant.state} #{applicant.zip}"

  .table-row class=(css if defined?(css))
    .table-cell.bold Phone:
    .table-cell
      - numbers = []
      - if applicant.phone_h.present?
        - numbers << "#{applicant.phone_h} (h)"
      - if applicant.phone_c.present?
        - numbers << "#{applicant.phone_c} (c)"
      - if applicant.phone_w.present?
        - numbers << "#{applicant.phone_w} (w)"
      - if applicant.fax.present?
        - numbers << "#{applicant.fax} (fax)"
      = safe_join(numbers, tag(:br))

  .table-row class=(css if defined?(css))
    .table-cell.bold Boat Type:
    .table-cell= applicant.boat_type
  - unless applicant.boat_type == 'None'
  .table-row class=(css if defined?(css))
    .table-cell.bold Boat Length:
    .table-cell= applicant.boat_length
  .table-row class=(css if defined?(css))
    .table-cell.bold Boat Name:
    .table-cell= applicant.boat_name

.table-row class=(css if defined?(css))
  .table-cell.bold Sea Scout?:
  .table-cell = applicant.sea_scout ? 'Yes' : 'No'

- if applicant.sig_other_name.present?
  .table-row class=(css if defined?(css))
    .table-cell.bold Significant Other's Name:
    .table-cell = applicant.sig_other_name

- if applicant.previous_certificate.present?
  .table-row class=(css if defined?(css))
    .table-cell.bold Previous Certificate:
    .table-cell = applicant.previous_certificate

app/views/member_applications/applied.html.slim
h1 Membership Application Submitted!

p
  - if @payment.paid
    | Y
  - else
    | Once you have paid your initial dues, y
  | our application will be reviewed, and you will be notified when its status is updated.

- if @payment.paid
  h4 Thank you for paying your initial annual dues of #{@payment.transaction_amount}!
- elsif @payment.parent.payable?
  h4 Your annual membership dues will be: #{@payment.transaction_amount}

  p
    | If you would like to pay now, you can do so below.
    br
    | If you'd rather pay later, you can close this tab now. There is a link to this page in your confirmation email.
  
  p.information.red Your application will not be considered complete until you have submitted your payment.

  = render 'braintree/dropin'

  p You can also mail a check payable to <b>Birmingham Power Squadron</b> to:

  p
    = content_tag(:ul, class: 'simple') do
      - @address.map do |row|
        = content_tag(:li, row)

app/views/member_applications/apply.js.erb
<%= render 'application/update_flashes' %>

app/views/member_applications/approve.js.erb
<%= render 'application/update_flashes' %>

$("#application_<%= @member_application.id %>").fadeOut();

app/views/member_applications/new.html.slim
h1 Membership Application

p Please provide the following information to apply to join our squadron!

p Once submitted, your application will be reviewed for approval, and you will be notified when its status is updated.

p
  b Annual membership fees:
  br
  ul.simple
    li Individual members are billed $89
    li Families are billed $134 + $1 / additional member

hr
= render('application/required_fields')

hr
#application
  = form_for @member_application, url: submit_application_path, method: :put, remote: true do |f|
    = render 'primary_applicant'
    = f.nested_fields_for :member_applicants do |ff|
      = render 'additional_applicant', ff: ff
    .center = f.add_nested_fields_link :member_applicants, 'Add an additional household member'
    hr
    p
      | I agree to contribute skills and time to further the objectives of
      br
      | <b>America's Boating Club – Birmingham Squadron</b>.
    .flexible.center = recaptcha_tags
    = spinner_button(f, css: 'big')

app/views/member_applications/review.html.slim
h1 Review Member Applications

- if @applications.present?
  p Approving an application will automatically invite all new members to choose a password on the website.

  p.red.italic Only approve an application here once ExCom has approved the application and dues have been received.

  - @applications.each do |app|
    .application-review id=("application_#{app.id}")
      .table
        .table-row
          .table-cell.bold Applied: 
          .table-cell = app.created_at.strftime(TimeHelper::LONG_TIME_FORMAT)
        .table-row
          .table-cell.bold Applicants: 
          .table-cell = app.member_applicants.count
        = render 'review_applicant', applicant: app.member_applicants.select(&:primary).first, css: 'blue'
        - app.member_applicants.reject(&:primary).each do |applicant|
          = render 'review_applicant', applicant: applicant
      = link_to 'Approve this application', approve_application_path(app.id), method: :patch, remote: true, class: 'big',
        data: { confirm: 'Are you sure you want to approve this application and invite all applicants to the website?', disable_with: (FA::Icon.p('spinner', style: :duotone, fa: 'spin-pulse') + 'Approving application...') }
- else
  h2.red There are currently no pending applications.